name = "Blawgcraft1.12"
author = "LilithClockwork"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10e36f54f8a22ed5d5549fb122e7aa0fffe35d3a24af69f7555f5176a22659b5"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
