name = "Blawgcraft1.12"
author = "LilithClockwork"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d432f56c710db08d893ed7e08cd3d8892aa07378b91a36a83091edeb80e32d9"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
