name = "Blawgcraft1.12"
author = "LilithClockwork"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75503736887f8bce12d1b3d807777d69fe2c13191ebcdffc957a37e3ac25cb70"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
